apiVersion: v1
kind: Pod
metadata:
  name: busybox-telnet
spec:
  containers:
  - name: busybox-telnet
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      while true; do
        sleep 10;
      done
